version: "3.7"

services:
  postgreDB:
    image: postgres
    container_name: postgres_reserveTicket
    ports:
      - 5435:5432
    volumes:
      - reserveTicket:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  reserveTicket:
